### ISSUE TITLE
Exception is thrown if no task is configured

### ISSUE THREAD

**Issue by josefglatz** [helhum/typo3-crontab#2]
I did following steps:
1. `composer req helhum/typo3-crontab`
2. cleared caches
3. DB COMPARE
4. open new TYPO3 backend module

The following exception appears
```
1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Invalid argument supplied for foreach() in /app/web/typo3conf/ext/crontab/Classes/Repository/TaskRepository.php line 23
```

**Comment by helhum** [comment]
Thanks. I indeed never tested without configured tasks :)
